name: Package and Upload to GCS

on:
  push:
    branches:
      - main

jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: copy requriements file to files
      run : cp requirements.txt files/requirements.txt
        
    - name: Build Package
      run: python setup.py sdist --formats=gztar

    - name: List Files
      run : ls
      
    - name: Upload to Google Cloud Storage
      uses: google-github-actions/upload-cloud-storage@v0.5.0
      with:
        path: dist/model-app-0.1.tar.gz
        destination: estimate-bucket
        credentials: ${{ secrets.GCP_SA_KEY }}
